{% set name = "cbonsai" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/jallbrit/{{ name }}/-/archive/v1.3.1/{{ name }}-v{{ version }}.tar.gz
  sha256: 62aa7e0eaf3098b7a6a2787146bd2531437df6ad0e604b0f9176128797efd8f9

build:
  skip: True  # [win]
  script:
    - make install CC=$CC PREFIX=$PREFIX
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - make
    - pkg-config
    - scdoc
  host:
    - ncurses

test:
  commands:
    - cbonsai --help

about:
  home: https://gitlab.com/jallbrit/cbonsai
  summary: grow bonsai trees in your terminal
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  dev_url: https://gitlab.com/jallbrit/cbonsai

extra:
  recipe-maintainers:
    - pavelzw
